swagger: "2.0"
info:
  version: 1.0.0
  title: Family Tree

basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /v1/users:
    get:
      summary: Get all users
      operationId: getUsers
      tags:
        - Users
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          $ref: '#/responses/Error'
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - Users
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/User'
        default:
          $ref: '#/responses/Error'

  /v1/users/{userId}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      tags:
        - Users
      parameters:
        - $ref: "#/parameters/UserIdPathParam"
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        default:
          $ref: '#/responses/Error'
    put:
      summary: Update a user by ID
      operationId: updateUserById
      tags:
        - Users
      parameters:
        - $ref: "#/parameters/UserIdPathParam"
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "204":
          description: No content
        default:
          $ref: '#/responses/Error'
    delete:
      tags:
        - Users
      summary: Deletes a user by ID
      operationId: deleteUserById
      parameters:
        - $ref: "#/parameters/UserIdPathParam"
      responses:
        "204":
          description: No content
        default:
          $ref: '#/responses/Error'

  /v1/trees:
    get:
      summary: Get all trees
      operationId: getTrees
      tags:
        - Trees
      parameters:
        - $ref: "#/parameters/UserIdQueryParam"
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Tree"
        default:
          $ref: '#/responses/Error'
    post:
      summary: Create a new tree
      operationId: createTree
      tags:
        - Trees
      parameters:
        - in: body
          name: tree
          required: true
          schema:
            $ref: "#/definitions/Tree"
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/Tree'
        default:
          $ref: '#/responses/Error'

  /v1/trees/{treeId}:
    get:
      summary: Get a tree by ID
      operationId: getTreeById
      tags:
        - Trees
      parameters:
        - $ref: "#/parameters/TreeIdPathParam"
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Tree'
        default:
          $ref: '#/responses/Error'
    put:
      summary: Update a tree by ID
      operationId: updateTreeById
      tags:
        - Trees
      parameters:
        - $ref: "#/parameters/TreeIdPathParam"
        - in: body
          name: tree
          required: true
          schema:
            $ref: "#/definitions/Tree"
      responses:
        "204":
          description: No content
        default:
          $ref: '#/responses/Error'
    delete:
      summary: Delete a tree by ID
      operationId: deleteTreeById
      tags:
        - Trees
      parameters:
        - $ref: "#/parameters/TreeIdPathParam"
      responses:
        "204":
          description: No content
        default:
          $ref: '#/responses/Error'

  /v1/people:
    get:
      summary: Get people in a tree
      operationId: getPeopleByTree
      tags:
        - People
      parameters:
        - $ref: "#/parameters/TreeIdQueryParam"
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Person"
        default:
          $ref: '#/responses/Error'
    post:
      summary: Create a new person in a tree
      operationId: createPersonForTree
      tags:
        - People
      parameters:
        - in: body
          name: person
          required: true
          schema:
            $ref: "#/definitions/Person"
      responses:
        "201":
          description: OK
          schema:
            $ref: "#/definitions/Person"
        default:
          $ref: "#/responses/Error"

  /v1/people/{personId}:
    put:
      summary: Update a person by ID
      operationId: updatePersonById
      tags:
        - People
      parameters:
        - $ref: "#/parameters/PersonIdPathParam"
        - in: body
          name: person
          required: true
          schema:
            $ref: "#/definitions/Person"
      responses:
        "204":
          description: No content
        default:
          $ref: "#/responses/Error"
    delete:
      summary: Delete a person by ID
      operationId: deletePersonById
      tags:
        - People
      parameters:
        - $ref: "#/parameters/PersonIdPathParam"
      responses:
        "204":
          description: No Content
        default:
          $ref: "#/responses/Error"

parameters:
  UserIdPathParam:
    in: path
    name: userId
    required: true
    type: string
    format: uuid

  UserIdQueryParam:
    in: query
    name: userId
    required: true
    type: string
    format: uuid

  TreeIdPathParam:
    in: path
    name: treeId
    required: true
    type: string
    format: uuid

  TreeIdQueryParam:
    in: query
    name: treeId
    required: true
    type: string
    format: uuid

  PersonIdPathParam:
    in: path
    name: personId
    required: true
    type: string
    format: uuid

definitions:
  User:
    type: object
    required:
      - login
      - name
    properties:
      id:
        type: string
        format: uuid
      login:
        type: string
      name:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
        format: password

  Person:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      tree_id:
        type: string
        format: uuid
      father_id:
        type: string
        format: uuid
      mother_id:
        type: string
        format: uuid
      children:
        type: array
        items:
          $ref: "#/definitions/Person"

  Tree:
    type: object
    required:
      - name
      - user_id
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      user_id:
        type: string
        format: uuid
        description: The ID of the user who owns the tree
      root_id:
        type: string
        format: uuid
        description: The ID of the root person in the tree, if any

responses:
  Error:
    description: An error occurred
    schema:
      type: object
      properties:
        message:
          type: string